### ISSUE TITLE
Webhook

### ISSUE THREAD

**Issue by Bryukh** [buganini/checkio-task-simple-hashlib#4]
Hi.
Could you add the webhook from here http://www.checkio.org/mission/simple_hashlib/admin/

It will allow update task automatically after any update in the repository.

**Comment by buganini** [comment]
@showjackyang Please check this, and consider merge this repo back to yours and update repo url in admin page.

**Comment by Bryukh** [comment]
Each mission has unique key and the webhook, so you can place they in each rep.

**Comment by Bryukh** [comment]
Sorry, I did not get -- in the mission this repository is placed, but the author is showjackyang.

**Comment by buganini** [comment]
Payload URL: http://www.checkio.org/mission/payload/?key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Content type: application/json
Secret: (blank)
Which events would you like to trigger this webhook? Just the push event.
Active: (uncheck)

Is this setting correct?

**Comment by Bryukh** [comment]
Oh. It should be "Active"

**Comment by buganini** [comment]
Oh, the "Active" should be checked.

**Comment by buganini** [comment]
BTW, a field for sample solution code in admin page may improve quality of publishing.

**Comment by Bryukh** [comment]
> BTW, a field for sample solution code in admin page may improve quality of publishing.

Hm, the interesting idea. Thanks!
